spring.application.name=Order Management System
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
