INSERT INTO role_permissions (role_id, permission_id)
SELECT '3c4a7d78-5558-4494-9e85-79be0564c1a2', id FROM permissions
WHERE name IN ('ORDER_READ', 'ORDER_CREATE', 'PRODUCT_READ', 'CATEGORY_READ', 'USER_READ', 'USER_UPDATE',
               'ORDER_UPDATE', 'ORDER_DELETE');

INSERT INTO role_permissions (role_id, permission_id)
SELECT '1bc13ce9-2106-49d2-af5c-019a91a1f794', id FROM permissions
WHERE name IN ('ORDER_READ', 'ORDER_CREATE', 'PRODUCT_READ', 'CATEGORY_READ', 'USER_READ', 'USER_UPDATE',
               'ORDER_READ_ALL', 'ORDER_UPDATE', 'ORDER_DELETE', 'PRODUCT_CREATE', 'PRODUCT_UPDATE',
               'CATEGORY_CREATE', 'CATEGORY_UPDATE', 'STATUS_MANAGE');

INSERT INTO role_permissions (role_id, permission_id)
SELECT 'eb87a8ac-ab4e-4250-83ec-e5edc8b50ca4', id FROM permissions
WHERE name IN ('ORDER_READ', 'ORDER_CREATE', 'PRODUCT_READ', 'CATEGORY_READ', 'USER_READ', 'USER_UPDATE',
               'ORDER_READ_ALL', 'ORDER_UPDATE', 'ORDER_DELETE', 'PRODUCT_CREATE', 'PRODUCT_UPDATE',
               'CATEGORY_CREATE', 'CATEGORY_UPDATE',
               'PRODUCT_DELETE', 'CATEGORY_DELETE', 'USER_READ_ALL', 'USER_UPDATE_ALL', 'USER_DELETE',
               'USER_ASSIGN_ROLE', 'STATUS_MANAGE', 'USER_SET_ROLE');